// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20220401232053_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Description = "Bites ankles to beg for food",
                            Name = "Matilda",
                            Sex = "F",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 1,
                            Description = "This kitten hides in plastic bags",
                            Name = "Caserole",
                            Sex = "M",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 4,
                            Description = "He only eats hotdogs with ketchup",
                            Name = "Nathan",
                            Sex = "M",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 12,
                            Description = "She's on her way out, tbh",
                            Name = "Brenda",
                            Sex = "F",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 1,
                            Description = "She stares at herself in the reflection",
                            Name = "Toothpick",
                            Sex = "F",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 1,
                            Description = "She can barely eat a kibble she's so smol",
                            Name = "Sea Shell Girl",
                            Sex = "F",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 3,
                            Description = "Will takes bites out of butter if left on the counter",
                            Name = "Butter",
                            Sex = "M",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 2,
                            Description = "Loves to nap in dog beds",
                            Name = "Oyster",
                            Sex = "F",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 2,
                            Description = "Just your basic golden retriever",
                            Name = "Chad",
                            Sex = "M",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
